eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: goods-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ishop?serverTimezone=GMT%2B8
  redis:
    password: Redis!@#
    host: 112.126.75.129
    port: 6379
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 20
        # 连接池中的最大空闲连接 默认 8
        max-idle: 10
        # 连接池中的最小空闲连接 默认 8
        min-idle: 8
    timeout: 300
  # 前端发送json字符串并将字符串转换成date对象
  jackson:
    time-zone: GMT+8
    serialization:
      #关闭jackson 对json做解析
      fail-on-empty-beans: false
rocketmq:
  name-server: 112.126.75.129:9876
  producer:
    group: i_group
    send-message-timeout: 30000
server:
  port: 8889
mybatis-plus:
  type-aliases-package: com.fc.ishop.dos
  global-config:
    db-config:
      id-type: auto
  configuration:
    use-generated-keys: true
  mapper-locations: classpath*:com.fc.ishop.mapper/*.xml
logging:
  level:
    com.fc.ishop: debug
ishop:
  rocketmq:
    promotion-group: promotion-group
    promotion-topic: promotion-topic
