eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: common-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ishop?serverTimezone=GMT%2B8
  redis:
    port: 6379
    password: Redis!@#
    host: 112.126.75.129
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 20
        # 连接池中的最大空闲连接 默认 8
        max-idle: 10
        # 连接池中的最小空闲连接 默认 8
        min-idle: 8
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
server:
  port: 8890
upload:
  commonHost: http://127.0.0.1:9000/common
  static-access-path: /upload/image/**
  base-path: D:/coding/img
  upload: /upload
  image: /image
ignored: # 公共网络请求，可访问
  urls:
    - /upload/image/**
